version: '3.4'
services:
  fastapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: fastapi
    volumes:
      - ./back/app/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./back/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    build:
      context: ./rdb
      dockerfile: Dockerfile
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data/
      - ./sql:/docker-compose-initdb.d
    env_file:
      - ./back/.env
    restart: always
    ports:
      - 5432:5432

volumes:
    postgres:
